/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfas;

/**
 *
 * @author Amada
 */
public class PanelDeCategorias extends javax.swing.JFrame {

    /**
     * Creates new form PanelDeCategorias
     */
    public PanelDeCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        categoexistentes = new javax.swing.JButton();
        caracteristicaproductos = new javax.swing.JButton();
        especificacionproductos = new javax.swing.JButton();
        asignacionCCE = new javax.swing.JButton();
        altaproducto = new javax.swing.JButton();
        bajaproducto = new javax.swing.JButton();
        modificacionproducto = new javax.swing.JButton();
        consideraciones = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelcategoria = new javax.swing.JLabel();
        salirgestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 233, 236));
        jPanel1.setForeground(new java.awt.Color(204, 153, 255));

        categoexistentes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        categoexistentes.setText("Categorias de Productos");
        categoexistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoexistentesActionPerformed(evt);
            }
        });

        caracteristicaproductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        caracteristicaproductos.setText("Caracteristicas de Productos ");
        caracteristicaproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caracteristicaproductosActionPerformed(evt);
            }
        });

        especificacionproductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        especificacionproductos.setText("Especificaciones de Productos ");
        especificacionproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especificacionproductosActionPerformed(evt);
            }
        });

        asignacionCCE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        asignacionCCE.setText("Asignacion CCE");
        asignacionCCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignacionCCEActionPerformed(evt);
            }
        });

        altaproducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        altaproducto.setText("Alta de Productos");
        altaproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaproductoActionPerformed(evt);
            }
        });

        bajaproducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bajaproducto.setText("Baja de Productos ");
        bajaproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaproductoActionPerformed(evt);
            }
        });

        modificacionproducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modificacionproducto.setText("Modificacion de producto");

        consideraciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        consideraciones.setText("Consideraciones adicionales ");

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        panelcategoria.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelcategoria.setText("GESTION DE PRODUCTOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(panelcategoria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelcategoria)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        salirgestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salirgestion.setText("Salir ");
        salirgestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirgestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(especificacionproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asignacionCCE, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caracteristicaproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoexistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificacionproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(altaproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bajaproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(consideraciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(salirgestion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(categoexistentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(caracteristicaproductos)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(altaproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bajaproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificacionproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especificacionproductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignacionCCE)
                    .addComponent(consideraciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(salirgestion)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoexistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoexistentesActionPerformed
        // TODO add your handling code here:
        categorias cate= new categorias();
        cate.setVisible(true);
    }//GEN-LAST:event_categoexistentesActionPerformed

    private void bajaproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaproductoActionPerformed
        // TODO add your handling code here:
        //Agregar productos a panel de categorias 
        BajaDeProductos bajaProduc = new BajaDeProductos();
        bajaProduc.setVisible(true);
    }//GEN-LAST:event_bajaproductoActionPerformed

    private void caracteristicaproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caracteristicaproductosActionPerformed
        // TODO add your handling code here:
        CaracteristicasDeProductos cateProduct = new CaracteristicasDeProductos();
        cateProduct.setVisible(true);
    }//GEN-LAST:event_caracteristicaproductosActionPerformed

    private void especificacionproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especificacionproductosActionPerformed
        // TODO add your handling code here:
        EspecificacionesDeProducto especiProducto = new EspecificacionesDeProducto();
        especiProducto.setVisible(true);
    }//GEN-LAST:event_especificacionproductosActionPerformed

    private void asignacionCCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignacionCCEActionPerformed
        // TODO add your handling code here:
        AsignacionDeCCE asigCCE = new AsignacionDeCCE();
        asigCCE.setVisible(true);
    }//GEN-LAST:event_asignacionCCEActionPerformed

    private void altaproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaproductoActionPerformed
        // TODO add your handling code here:
        Productos productoAlta = new Productos();
        productoAlta.setVisible(true);
    }//GEN-LAST:event_altaproductoActionPerformed

    private void salirgestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirgestionActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirgestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDeCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDeCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDeCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDeCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDeCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaproducto;
    private javax.swing.JButton asignacionCCE;
    private javax.swing.JButton bajaproducto;
    private javax.swing.JButton caracteristicaproductos;
    private javax.swing.JButton categoexistentes;
    private javax.swing.JButton consideraciones;
    private javax.swing.JButton especificacionproductos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modificacionproducto;
    private javax.swing.JLabel panelcategoria;
    private javax.swing.JButton salirgestion;
    // End of variables declaration//GEN-END:variables
}
